### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Lucas-C** [bzg/covid19-floss-initatives#1]
Hi !

Thanks for putting this up.

Just a detail : the links are broken (Markdown issue ?) on https://bzg.github.io/covid19-floss-initatives/

**Comment by bzg** [comment]
Thanks for your feedback!

Yes, I don't know how to inline links in GitHub-flavor markdown tables.  It is quite readable in the .org version [here](https://github.com/bzg/covid19-floss-initatives/blob/master/index.org).

If you have any suggestion, that's great.

**Comment by Lucas-C** [comment]
I think you just need to remove the brackets `<>`, GitHub will auto-detect hyperlinks

**Comment by bzg** [comment]
I've completely revamped the index.md page and now links are fine on https://bzg.github.io/covid19-floss-initatives/

It's still a work in progress: if you can help with adding descriptions and other useful informations, that'd be greatly appreciated!

Thanks.
