### ISSUE TITLE
https://github.com/opendatakit

### ISSUE THREAD

**Issue by bzg** [bzg/covid19-floss-initatives#5]
https://github.com/opendatakit/ via https://twitter.com/MathieuBossaert/status/1243501871077249025

**Comment by mathieubossaert** [comment]
Avec ce formulaire notamment, spécifique au protocole d’enquête de l'OMS sur le COVID :
https://forum.opendatakit.org/t/who-covid-19-minimum-reporting-form/25647

**Comment by mathieubossaert** [comment]
Un nouveau formulaire de l'OMS a été créé pour ODK :
https://forum.getodk.org/t/who-covid-19-contact-tracing-form/26123

**Comment by bzg** [comment]
Merci - je prendrai le temps de mettre à jour l'ensemble du dépôt d'ici une semaine, j'ai malheureusement peu de disponibilités avant.
